[env:xiao_c6]
; ESP32-C6 + Arduino core 3.x wymaga platformy pioarduino (oficjalna espressif32 nie wspiera C6 w Arduino)
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
